select * from Walmart_customer_purchases

--Q1: What is the total revenue generated by categories?
select 
category,
cast(sum(purchase_amount) as decimal(10,2)) as total_revenue
from Walmart_customer_purchases
group by category
order by total_revenue desc

--Q2: Which age group contributes the most revenue?
select
age_group,
cast(sum(purchase_amount) as decimal(10,2)) as total_revenue
from Walmart_customer_purchases
group by age_group
order by total_revenue desc

--Q3: Which categories receive the highest average rating?
select
category,
avg(rating) as avg_rating
from Walmart_customer_purchases
group by category
order by avg_rating desc

--Q4: Which payment method generates the highest average purchase amount?
select
payment_method,
avg(purchase_amount) as avg_revenue
from Walmart_customer_purchases
group by payment_method
order by avg_revenue desc

--Q5: Which are the top 5 city having the highest repeat customer number?
select top 5
city,
count(case when repeat_customer = 'Yes' then 1 end) as repeat_customer_number
from Walmart_customer_purchases
group by city
order by repeat_customer_number desc

--Q6: Which genders generate the highest revenue after applying discount?
select
gender,
cast(sum(purchase_amount) as decimal(10,2)) as total_revenue
from Walmart_customer_purchases
where discount_applied = 'Yes'
group by gender
order by total_revenue desc

--Q7: What are the top 3 products by revenue in each category?
with ranked_products as(
select
category,
product_name,
cast(sum(purchase_amount) as decimal(10,2)) as total_revenue,
row_number() over(partition by category order by cast(sum(purchase_amount) as decimal(10,2)) desc) as rn
from Walmart_customer_purchases
group by category, product_name
)
select
category,
product_name,
total_revenue
from ranked_products
where rn <= 3
order by category, total_revenue DESC;

--Q8: What is the monthly revenue growth rate?
with monthly_revenue as(
select 
datetrunc(month, purchase_date) as month_date,
cast(sum(purchase_amount) as decimal(10,2)) as total_revenue,
lag(cast(sum(purchase_amount) as decimal(10,2))) over(order by datetrunc(month, purchase_date)) as pre_month_revenue
from Walmart_customer_purchases
group by datetrunc(month, purchase_date)
)
select
month_date,
total_revenue,
pre_month_revenue,
round(100.0 * (total_revenue - pre_month_revenue) / NULLIF(pre_month_revenue, 0), 2) as monthly_growth_rate
from monthly_revenue
order by month_date

--Q9: Which top 5 cities have revenue above the average city revenue?
with city_revenue as(
select 
city,
cast(sum(purchase_amount) as decimal(10,2)) as total_city_revenue
from Walmart_customer_purchases
group by city
)
, city_avg as(
select avg(total_city_revenue) as avg_city_revenue
from city_revenue
)
select top 5
city,
total_city_revenue,
round(cr.total_city_revenue / ca.avg_city_revenue, 2) AS total_times_avg
from city_revenue cr
cross join city_avg ca
where cr.total_city_revenue > ca.avg_city_revenue
order by cr.total_city_revenue desc;

--Q10: Which products show the strongest month-over-month revenue growth?
with products_revenue_per_month as(
select
product_name,
datetrunc(month, purchase_date) as monthly,
sum(purchase_amount) as monthly_product_revenue
from Walmart_customer_purchases
group by datetrunc(month, purchase_date), product_name
)
,pre_monthly_product as(
select
product_name,
monthly,
monthly_product_revenue,
lag(monthly_product_revenue) over(order by monthly) as pre_monthly_product_revenue
from products_revenue_per_month
)
select
product_name,
monthly,
monthly_product_revenue,
pre_monthly_product_revenue,
ROUND(100.0 * (monthly_product_revenue - pre_monthly_product_revenue) / NULLIF(pre_monthly_product_revenue, 0),2) AS mon_growth_percent
from pre_monthly_product
where pre_monthly_product_revenue IS NOT NULL
order by mon_growth_percent desc



